"""Order book interface and the Phase 1 SortedDict-backed implementation stub."""

from abc import ABC, abstractmethod

from sortedcontainers import SortedDict

from lob.order import Order, Trade
from lob.price_level import PriceLevel


class OrderBook(ABC):
    """Abstract limit order book for a single instrument.

    The method signatures on this class are a contract. Propose changes in an issue first.
    """

    @abstractmethod
    def add(self, order: Order) -> list[Trade]:
        """Submit ``order`` to the book.

        Matches the incoming order against the opposite side using strict price-time
        priority. Trades execute at the resting order's price. Any unfilled remainder of a
        limit order rests on the book with the order's original timestamp.

        Returns:
            Trades generated by this call, in execution order. Empty if nothing matched.
        """

    @abstractmethod
    def cancel(self, order_id: int) -> bool:
        """Cancel a resting order.

        Lookup of ``order_id`` must be O(1).

        Returns:
            True if the order was resting and has been removed, False if not found.
        """

    @abstractmethod
    def best_bid(self) -> int | None:
        """Return the highest resting bid price in ticks, or None if there are no bids."""

    @abstractmethod
    def best_ask(self) -> int | None:
        """Return the lowest resting ask price in ticks, or None if there are no asks."""

    def spread(self) -> int | None:
        """Return ``best_ask - best_bid`` in ticks, or None if either side is empty."""
        bid = self.best_bid()
        ask = self.best_ask()
        if bid is None or ask is None:
            return None
        return ask - bid

    @abstractmethod
    def depth(self, levels: int = 5) -> dict[str, list[tuple[int, int]]]:
        """Return aggregated depth for the top ``levels`` price levels per side.

        Returns:
            ``{"bids": [(price, total_qty), ...], "asks": [(price, total_qty), ...]}``,
            each list ordered best price first.
        """


class SortedDictOrderBook(OrderBook):
    """Order book backed by ``SortedDict`` (price -> PriceLevel) per side.

    A ``dict[int, Order]`` index provides O(1) lookup for cancels.
    """

    def __init__(self) -> None:
        self._bids: SortedDict[int, PriceLevel] = SortedDict()
        self._asks: SortedDict[int, PriceLevel] = SortedDict()
        self._orders: dict[int, Order] = {}

    def add(self, order: Order) -> list[Trade]:
        # TODO(Phase 1)
        raise NotImplementedError

    def cancel(self, order_id: int) -> bool:
        # TODO(Phase 1)
        raise NotImplementedError

    def best_bid(self) -> int | None:
        # TODO(Phase 1)
        raise NotImplementedError

    def best_ask(self) -> int | None:
        # TODO(Phase 1)
        raise NotImplementedError

    def depth(self, levels: int = 5) -> dict[str, list[tuple[int, int]]]:
        # TODO(Phase 1)
        raise NotImplementedError
